// Generated by CoffeeScript 1.8.0
(function() {
  window.Model || (window.Model = {});

  window.Model.MainQuestFactory = (function() {
    function MainQuestFactory() {}

    MainQuestFactory.createQuests = function(intro, ending) {
      var i, numSubQuests, subQuest, subQuests, _i;
      numSubQuests = 2 + Math.floor(Math.random() * 3);
      subQuests = [];
      for (i = _i = 0; 0 <= numSubQuests ? _i <= numSubQuests : _i >= numSubQuests; i = 0 <= numSubQuests ? ++_i : --_i) {
        subQuest = window.Model.Quest.create('PowerUp');
        subQuests.push(subQuest);
      }
      return subQuests;
    };

    return MainQuestFactory;

  })();

}).call(this);
