// Generated by CoffeeScript 1.8.0
(function() {
  window.Model || (window.Model = {});

  window.CreateWorld = (function() {
    function CreateWorld() {}

    CreateWorld.prototype.create = function() {
      var ending, i, intro, mainQuests, q, quest, quests, _i, _j, _len, _len1;
      this.game.data.seed = 1;
      console.info("Game world: " + this.game.data.seed);
      Math.seedrandom(this.game.data.seed);
      this.game.data.world = window.Model.WorldGenerator.generate(2, 2);
      intro = window.Model.Quest.create("Introduction");
      ending = window.Model.Quest.create("FinalBattle");
      mainQuests = window.Model.Quest.createMainQuests(intro, ending);
      quests = [];
      quests.push(intro);
      for (i = _i = 0, _len = mainQuests.length; _i < _len; i = ++_i) {
        q = mainQuests[i];
        quests.push(q);
      }
      quests.push(ending);
      this.game.data.quests = quests;
      console.debug("Quests:");
      for (i = _j = 0, _len1 = quests.length; _j < _len1; i = ++_j) {
        quest = quests[i];
        console.debug("\t" + (i + 1) + ": " + quest);
      }
      Math.seedrandom();
      return this.game.state.start('coreGame');
    };

    return CreateWorld;

  })();

}).call(this);
