// Generated by CoffeeScript 1.8.0
(function() {
  var TILE_INDICIES;

  window.Model || (window.Model = {});

  TILE_INDICIES = {
    'clear': 0,
    'wall': 1
  };

  window.Model.Map = (function() {
    function Map(width, height) {
      var current, tile, x, y, _i, _j, _ref, _ref1;
      this.width = width;
      this.height = height;
      this.tiles = [];
      for (x = _i = 0, _ref = this.width; 0 <= _ref ? _i < _ref : _i > _ref; x = 0 <= _ref ? ++_i : --_i) {
        current = [];
        for (y = _j = 0, _ref1 = this.height; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
          tile = TILE_INDICIES['clear'];
          if (x === 0 || y === 0 || x === this.width - 1 || y === this.height - 1) {
            tile = TILE_INDICIES['wall'];
          }
          current.push(tile);
        }
        this.tiles.push(current);
      }
      this.transitions = [];
    }

    Map.prototype.get = function(x, y) {
      return this.tiles[x][y];
    };

    Map.prototype.clear = function(x, y) {
      return this.tiles[x][y] = TILE_INDICIES['clear'];
    };

    Map.prototype.addTransition = function(t) {
      var dupe, e, _i, _len, _ref;
      _ref = this.transitions;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        e = _ref[_i];
        if (e.x === t.x && e.y === t.y) {
          dupe = e;
        }
      }
      if (dupe == null) {
        return this.transitions.push(t);
      }
    };

    Map.prototype.transitionAt = function(x, y) {
      var t, _i, _len, _ref;
      _ref = this.transitions;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        t = _ref[_i];
        if (t.x === x && t.y === y) {
          return t;
        }
      }
    };

    Map.prototype.toString = function() {
      return "Map (" + this.x + ", " + this.y + ")";
    };

    return Map;

  })();

}).call(this);
