// Generated by CoffeeScript 1.8.0
(function() {
  window.Model || (window.Model = {});

  window.Model.WorldGenerator = (function() {
    function WorldGenerator() {}

    WorldGenerator.generate = function(width, height) {
      return new window.Model.World(width, height);
    };

    return WorldGenerator;

  })();

}).call(this);
