// Generated by CoffeeScript 1.8.0
(function() {
  var State;

  State = (function() {
    function State() {}

    State.prototype.preload = function() {
      return game.load.image('logo', 'assets/graphics/phaser.png');
    };

    State.prototype.create = function() {
      var logo;
      logo = game.add.sprite(game.world.centerX, game.world.centerY, 'logo');
      return logo.anchor.setTo(0.5, 0.5);
    };

    return State;

  })();

  window.onload = function() {
    return this.game = new Phaser.Game(800, 600, Phaser.AUTO, '', new State);
  };

}).call(this);
