// Generated by CoffeeScript 1.8.0
(function() {
  window.Classes = (function() {
    function Classes() {}

    Classes.data = {};

    Classes.register = function(key, clazz) {
      return Classes.data[key] = clazz;
    };

    Classes.get = function(keySubstring) {
      var candidates, key, _i, _len;
      candidates = Object.keys(Classes.data).filter(function(key) {
        return key.indexOf(keySubstring) > -1;
      });
      if (candidates.length === 0) {
        throw "Can't find a class matching " + keySubstring + "; options are: " + (Object.keys(Classes.data));
      }
      if (candidates.length === 1) {
        return Classes.data[candidates[0]];
      }
      for (_i = 0, _len = candidates.length; _i < _len; _i++) {
        key = candidates[_i];
        if (key.indexOf("." + keySubstring) === key.length - keySubstring.length - 1) {
          return Classes.data[key];
        }
      }
      throw "Found multiple classes for " + keySubstring + ": " + candidates;
    };

    return Classes;

  })();

}).call(this);
