// Generated by CoffeeScript 1.8.0
(function() {
  var DEBUG_MODE, log;

  DEBUG_MODE = /[?&]debug=/.test(location.href);

  window.toggleConsole = function() {
    var console, link, showIt;
    console = document.getElementById('console');
    link = document.getElementById('toggleConsole');
    showIt = console.style.display === 'none';
    if (showIt) {
      console.style.display = 'block';
      return link.innerText = 'Hide Console';
    } else {
      console.style.display = 'none';
      return link.innerText = 'Show Console';
    }
  };

  window.clearConsole = function() {
    return document.getElementById('console').innerHTML = '';
  };

  log = function(color, message) {
    var html;
    html = "<p style='color: " + color + ";'>" + message + "</span></p>";
    return document.getElementById('console').innerHTML += html;
  };

  if (typeof window.console !== 'undefined' && typeof window.console.log !== 'undefined') {
    window.console.olog = window.console.log;
  } else {
    window.console.olog = function() {};
  }

  window.console.debug = function(message) {
    if (DEBUG_MODE) {
      window.console.olog(message);
      return log('#888', message);
    }
  };

  window.console.error = function(message) {
    window.console.olog(message);
    return log('#f00', message);
  };

  window.onerror = function(message, url, lineNumber) {
    return window.console.error("" + url + "\tline " + lineNumber + ":<br />" + message);
  };

  window.console.info = function(message) {
    if (DEBUG_MODE) {
      window.console.olog(message);
      return log('#00f', message);
    }
  };

  window.console.log = window.console.debug;

}).call(this);
