// Generated by CoffeeScript 1.8.0
(function() {
  var MapTransition;

  MapTransition = (function() {
    function MapTransition(x, y, destination, destX, destY, direction) {
      this.x = x;
      this.y = y;
      this.destination = destination;
      this.destX = destX;
      this.destY = destY;
      this.direction = direction;
    }

    return MapTransition;

  })();

  window.Classes.register('soe.model.events.MapTransition', MapTransition);

}).call(this);
